#!/usr/bin/env python3
"""Session management commands for Subumbra bootstrap."""

from __future__ import annotations

from subumbra_keys import (
    _effective_session_adapter_ids,
    _effective_session_key_ids,
    _ensure_session_start_has_no_overlap,
    _expire_active_sessions,
    _fmt_duration,
    _fmt_utc_ts,
    _format_session_scope,
    _get_session_row_by_id,
    _list_active_session_rows,
    _load_active_session_static_adapters,
    _load_keys_payload_or_die,
    _load_live_key_ids,
    _load_runtime_adapter_registry,
    _open_session_db,
    _parse_session_csv_arg,
    _parse_session_duration_seconds,
    _print_session_row,
    _reconcile_active_adapter_gate,
    _reconcile_active_adapter_gates,
    _session_arg_value,
    _session_args,
    _session_remaining_ttl_seconds,
    _session_row_to_dict,
    _session_scope_from_db_value,
    _session_scope_to_db_value,
    _session_wizard,
    _ssh_session_scope_key,
    _ssh_session_scope_pairs,
    _get_push_registry_cf_creds,
    _is_revoked_record,
    _kv_delete_key,
    _kv_put_text_value,
    _load_kv_namespace_id,
    _resolve_session_adapter_scope,
    _resolve_session_key_scope,
    run_session_end,
    run_session_list,
    run_session_start,
    run_session_status,
)
