"""
Subumbra Adapter #1 — LiteLLM
─────────────────────────────────────────────────
This file implements the LiteLLM adapter for Subumbra. LiteLLM now reaches the
Subumbra core through the canonical POST /proxy API using a custom transport.

Canonical Subumbra core API: POST /proxy — see docs/adapter-contract.md

The callback fetches subumbra records and injects V2 envelope metadata. The
transport owns /proxy packaging and sends the fully assembled upstream request
to the Worker. The old header-gated compatibility route is gone.

─────────────────────────────────────────────────
Intercepts any LiteLLM call whose api_key starts with "subumbra:" and:

  1. Extracts the key_id (e.g. "subumbra:anthropic_prod" → "anthropic_prod")
  2. Fetches the AES-256-GCM ciphertext from subumbra-keys  (internal network)
  3. Injects the Subumbra envelope metadata needed by the transport
  4. Logs success/failure for the UI dashboard

How routing works now:
  LiteLLM builds its native provider request URL first.

  The callback injects:
    X-Subumbra-Provider     → required mismatch-protection identity
    X-Subumbra-Ciphertext   → encrypted API key envelope
    X-Subumbra-Wrapped-Dek  → RSA-wrapped per-record DEK
    X-Subumbra-Pub-Key-Fp   → wrapping key fingerprint
    X-Subumbra-Key-Id       → AAD-bound record identity

  SubumbraTransport intercepts the outbound request, strips internal headers,
  packages the request into the canonical /proxy JSON envelope, and sends it to
  the Worker. The Worker validates, decrypts, injects auth, and proxies to the
  real upstream.

Hook used: async_pre_call_deployment_hook
  This fires AFTER the router selects a deployment and api_key from litellm_params
  is available in kwargs. async_pre_call_hook fires too early (proxy request level)
  before the model's api_key is resolved from config.

Required environment variables (set in docker-compose.yml, not secrets):
  SUBUMBRA_KEYS_URL      http://subumbra-keys:9090
  SUBUMBRA_ACCESS_TOKEN  hex token (generated by bootstrap)
  SUBUMBRA_HMAC_KEY      hex key   (generated by bootstrap)
  CF_WORKER_URL          https://subumbra-proxy.workers.dev

Optional:
  CF_ACCESS_CLIENT_ID       CF Access service token (if Worker is behind CF Access)
  CF_ACCESS_CLIENT_SECRET
"""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import json
import logging
import os
import secrets
import time
from typing import Optional

import httpx
from litellm.integrations.custom_logger import CustomLogger

# ─────────────────────────────────────────────────────────────────────────────
# Configuration  (read once at module load)
# ─────────────────────────────────────────────────────────────────────────────

SUBUMBRA_KEYS_URL       = os.environ.get("SUBUMBRA_KEYS_URL",       "http://subumbra-keys:9090").rstrip("/")
SUBUMBRA_ACCESS_TOKEN   = os.environ.get("SUBUMBRA_ACCESS_TOKEN",   "")
SUBUMBRA_HMAC_KEY       = os.environ.get("SUBUMBRA_HMAC_KEY",       "").encode()
CF_WORKER_URL         = os.environ.get("CF_WORKER_URL",         "").rstrip("/")
CF_ACCESS_CLIENT_ID   = os.environ.get("CF_ACCESS_CLIENT_ID",   "")
CF_ACCESS_CLIENT_SECRET = os.environ.get("CF_ACCESS_CLIENT_SECRET", "")

# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────

log = logging.getLogger("subumbra-callback")

TRANSPORT_STRIP_HEADERS = {
    "cf-cache-status",
    "cf-ray",
    "nel",
    "report-to",
    "alt-svc",
    "server",
}

# Warn at import time if critical vars are absent — helps with misconfiguration
# debugging without failing hard (LiteLLM still starts, non-Subumbra models work).
if not SUBUMBRA_ACCESS_TOKEN:
    log.warning("subumbra-callback: SUBUMBRA_ACCESS_TOKEN not set — subumbra: keys will fail")
if not SUBUMBRA_HMAC_KEY:
    log.warning("subumbra-callback: SUBUMBRA_HMAC_KEY not set — subumbra: keys will fail")
if not CF_WORKER_URL:
    log.warning("subumbra-callback: CF_WORKER_URL not set — subumbra: keys will fail")

def _json_error_response(request: httpx.Request, status_code: int, message: str) -> httpx.Response:
    return httpx.Response(
        status_code,
        headers={"content-type": "application/json"},
        content=json.dumps({"error": message}).encode(),
        request=request,
    )


def _is_json_content_type(content_type: str) -> bool:
    media_type = content_type.split(";", 1)[0].strip().lower()
    return media_type == "application/json" or media_type.endswith("+json")


class _WorkerStream(httpx.AsyncByteStream):
    def __init__(self, response: httpx.Response, context_manager) -> None:
        self._response = response
        self._context_manager = context_manager
        self._closed = False

    async def __aiter__(self):
        try:
            async for chunk in self._response.aiter_raw():
                yield chunk
        finally:
            await self.aclose()

    async def aclose(self) -> None:
        if self._closed:
            return
        self._closed = True
        await self._context_manager.__aexit__(None, None, None)


class SubumbraTransport(httpx.AsyncBaseTransport):
    def __init__(self) -> None:
        self._passthrough = httpx.AsyncHTTPTransport()
        self._worker_client = httpx.AsyncClient(
            timeout=httpx.Timeout(connect=10.0, read=120.0, write=30.0, pool=30.0),
            limits=httpx.Limits(max_connections=20, max_keepalive_connections=10),
        )

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        ciphertext = request.headers.get("X-Subumbra-Ciphertext")
        if not ciphertext:
            return await self._passthrough.handle_async_request(request)

        content_type = request.headers.get("content-type", "")
        if content_type and not _is_json_content_type(content_type):
            return _json_error_response(request, 415, "unsupported content-type")

        body = None
        raw_body = await request.aread()
        if raw_body:
            try:
                body = json.loads(raw_body.decode("utf-8"))
            except Exception:
                return _json_error_response(request, 400, "request body must be JSON")

        clean_headers: dict[str, str] = {}
        for key, value in request.headers.items():
            key_l = key.lower()
            if key_l.startswith("x-subumbra-"):
                continue
            if key_l == "authorization":
                continue
            if key_l in {"cf-access-client-id", "cf-access-client-secret"}:
                continue
            clean_headers[key] = value

        target_url = str(request.url)
        provider = request.headers.get("X-Subumbra-Provider", "")
        proxy_payload = {
            "ciphertext": ciphertext,
            "provider": provider,
            "target_url": target_url,
            "method": request.method,
            "headers": clean_headers,
            "body": body,
            "wrapped_dek": request.headers.get("X-Subumbra-Wrapped-Dek", ""),
            "pub_key_fp": request.headers.get("X-Subumbra-Pub-Key-Fp", ""),
            "key_id": request.headers.get("X-Subumbra-Key-Id", ""),
            "enc_version": 2,
        }

        outer_headers = {
            "Content-Type": "application/json",
            "X-Subumbra-Token": SUBUMBRA_ACCESS_TOKEN,
        }
        if CF_ACCESS_CLIENT_ID:
            outer_headers["CF-Access-Client-Id"] = CF_ACCESS_CLIENT_ID
            outer_headers["CF-Access-Client-Secret"] = CF_ACCESS_CLIENT_SECRET

        log.info(
            "subumbra-transport: intercept provider=%s method=%s target_url=%s route=/proxy",
            provider,
            request.method,
            target_url,
        )

        stream_cm = self._worker_client.stream(
            "POST",
            f"{CF_WORKER_URL}/proxy",
            headers=outer_headers,
            json=proxy_payload,
        )
        worker_response = await stream_cm.__aenter__()
        if worker_response.status_code >= 400:
            log.warning(
                "subumbra-transport: worker failure provider=%s method=%s target_url=%s status=%s",
                provider,
                request.method,
                target_url,
                worker_response.status_code,
            )
        response_headers = {
            key: value
            for key, value in worker_response.headers.items()
            if key.lower() not in TRANSPORT_STRIP_HEADERS
        }
        return httpx.Response(
            worker_response.status_code,
            headers=response_headers,
            stream=_WorkerStream(worker_response, stream_cm),
            request=request,
        )


_subumbra_client: httpx.AsyncClient | None = None


def _wire_transport_once() -> None:
    """
    Wire SubumbraTransport into LiteLLM's HTTP clients.

    Called on every Subumbra request. Creates _subumbra_client once, then
    re-applies the wiring on each call so that handlers replaced by
    LiteLLM's 1-hour TTL cache eviction are always re-patched before use.
    """
    global _subumbra_client

    import litellm as _litellm
    from litellm.llms.custom_httpx.http_handler import get_async_httpx_client

    if not hasattr(_litellm, "module_level_aclient") or not hasattr(_litellm.module_level_aclient, "client"):
        raise RuntimeError(
                "Subumbra transport wiring requires litellm.module_level_aclient.client; "
            "current LiteLLM build does not expose that path"
        )

    if _subumbra_client is None:
        _subumbra_client = httpx.AsyncClient(transport=SubumbraTransport())

    _litellm.module_level_aclient.client = _subumbra_client
    _litellm.aclient_session = _subumbra_client

    for provider_name, provider, params in (
        ("anthropic",  _litellm.LlmProviders.ANTHROPIC,   None),
        ("groq",       _litellm.LlmProviders.GROQ,         {"ssl_verify": None}),
        ("deepseek",   _litellm.LlmProviders.DEEPSEEK,     {"ssl_verify": None}),
        # These providers use base_llm_http_handler → AsyncHTTPHandler (not AsyncOpenAI SDK).
        # Wire their handler.client directly so SubumbraTransport intercepts their requests.
        # params must match what BaseLLMHTTPHandler passes: {"ssl_verify": None}
        ("openrouter", _litellm.LlmProviders.OPENROUTER,   {"ssl_verify": None}),
        ("mistral",    _litellm.LlmProviders.MISTRAL,      {"ssl_verify": None}),
        ("xai",        _litellm.LlmProviders.XAI,          {"ssl_verify": None}),
    ):
        handler = get_async_httpx_client(llm_provider=provider, params=params)
        if not hasattr(handler, "client"):
            raise RuntimeError(
                f"Subumbra transport wiring requires "
                f"get_async_httpx_client({provider_name}).client"
            )
        handler.client = _subumbra_client


# ─────────────────────────────────────────────────────────────────────────────
# Subumbra callback
# ─────────────────────────────────────────────────────────────────────────────

class ForgeKeyCallback(CustomLogger):
    """
    LiteLLM CustomLogger that intercepts "subumbra:" api_key values, fetches the
    V2 Subumbra envelope, and prepares the request for transport-owned /proxy
    packaging.
    """

    def __init__(self) -> None:
        super().__init__()
        # Shared async HTTP client — keeps a connection pool to subumbra-keys
        self._http = httpx.AsyncClient(
            timeout=httpx.Timeout(connect=3.0, read=10.0, write=5.0, pool=5.0),
            limits=httpx.Limits(max_connections=20, max_keepalive_connections=10),
        )

    # ── internal helpers ──────────────────────────────────────────────────────

    def _subumbra_headers(self, key_id: str) -> dict[str, str]:
        """
        Build the four headers required by subumbra-keys for a ciphertext fetch:
          X-Subumbra-Token      — bearer token
          X-Subumbra-Timestamp  — current epoch seconds
          X-Subumbra-Nonce      — single-use hex nonce
          X-Subumbra-Signature  — HMAC-SHA256(f"{key_id}:{timestamp}:{nonce}", SUBUMBRA_HMAC_KEY)

        The signature and nonce prevent replay attacks; subumbra-keys rejects
        reused requests and timestamps older than 30 s.
        """
        timestamp = str(int(time.time()))
        nonce = secrets.token_hex(16)
        sig = hmac.new(
            SUBUMBRA_HMAC_KEY,
            f"{key_id}:{timestamp}:{nonce}".encode(),
            hashlib.sha256,
        ).hexdigest()
        return {
            "X-Subumbra-Token":     SUBUMBRA_ACCESS_TOKEN,
            "X-Subumbra-Timestamp": timestamp,
            "X-Subumbra-Nonce":     nonce,
            "X-Subumbra-Signature": sig,
        }

    async def _fetch_subumbra_record(self, key_id: str) -> dict:
        """
        Fetch the V2 envelope record for key_id from subumbra-keys.

        Returns the full response dict:
          {key_id, ciphertext, provider, target_host, wrapped_dek, pub_key_fp, enc_version}

        Raises:
            httpx.HTTPStatusError  if subumbra-keys returns a non-2xx status
            httpx.RequestError     if subumbra-keys is unreachable
        """
        headers  = self._subumbra_headers(key_id)
        url      = f"{SUBUMBRA_KEYS_URL}/keys/{key_id}"

        response = await self._http.get(url, headers=headers)
        response.raise_for_status()

        return response.json()

    # ── LiteLLM hook ──────────────────────────────────────────────────────────

    async def async_pre_call_deployment_hook(
        self,
        kwargs: dict,
        call_type,
    ) -> Optional[dict]:
        """
        Called by LiteLLM AFTER a deployment is selected, BEFORE the API call
        is sent. At this point kwargs["api_key"] contains the model's api_key
        from litellm_params (e.g. "subumbra:groq_prod").

        If api_key starts with "subumbra:", injects the Subumbra envelope metadata
        needed by SubumbraTransport. The transport then packages the fully
        assembled request into the canonical /proxy envelope. All other calls
        pass through unchanged.

        Note: async_pre_call_hook fires too early (proxy request level, before
        deployment selection) and does not have access to the model's api_key.
        This hook fires at the right point in the call chain.
        """
        api_key = kwargs.get("api_key", "")
        if not isinstance(api_key, str) or not api_key.startswith("subumbra:"):
            return None

        key_id = api_key[len("subumbra:"):]
        if not key_id:
            raise ValueError("subumbra: api_key has empty key_id (expected 'subumbra:key_id')")

        # ── 1. Validate config ────────────────────────────────────────────────
        if not CF_WORKER_URL:
            raise RuntimeError(
                "CF_WORKER_URL is not set — cannot route subumbra key through CF Worker"
            )
        if not SUBUMBRA_ACCESS_TOKEN or not SUBUMBRA_HMAC_KEY:
            raise RuntimeError(
                "SUBUMBRA_ACCESS_TOKEN / SUBUMBRA_HMAC_KEY not set — run bootstrap first"
            )
        _wire_transport_once()

        # ── 2. Fetch V2 envelope record from subumbra-keys (with retry) ─────
        # HTTPStatusError (4xx/5xx) is not retried — it means the key is missing
        # or the token is wrong, and retrying will not help.
        # RequestError (network) is retried up to 3 times with exponential backoff.
        _last_net_exc: Exception | None = None
        for _attempt in range(3):
            try:
                record = await self._fetch_subumbra_record(key_id)
                break
            except httpx.HTTPStatusError as exc:
                log.error(
                    "subumbra-callback: subumbra-keys returned %s for key_id=%s",
                    exc.response.status_code, key_id,
                )
                raise RuntimeError(
                    f"subumbra-keys returned {exc.response.status_code} for key_id={key_id}"
                ) from exc
            except httpx.RequestError as exc:
                _last_net_exc = exc
                if _attempt < 2:
                    _wait = 0.1 * (2 ** _attempt)  # 0.1 s, 0.2 s
                    log.warning(
                        "subumbra-callback: subumbra-keys unreachable (attempt %d/3), "
                        "retry in %.1fs: %s",
                        _attempt + 1, _wait, exc,
                    )
                    await asyncio.sleep(_wait)
        else:
            log.error(
                "subumbra-callback: subumbra-keys unreachable after 3 attempts: %s",
                _last_net_exc,
            )
            raise RuntimeError("subumbra-keys service is unreachable") from _last_net_exc

        # Extract V2 envelope fields
        provider    = record["provider"]
        ciphertext  = record["ciphertext"]
        wrapped_dek = record.get("wrapped_dek")
        pub_key_fp  = record.get("pub_key_fp")
        enc_version = record.get("enc_version", 1)

        # Hard-reject non-V2 records (belt-and-suspenders — Worker also rejects)
        if enc_version != 2 or not wrapped_dek:
            raise RuntimeError(
                f"subumbra-keys returned a non-V2 record for key_id={key_id!r} "
                f"(enc_version={enc_version}) — re-run bootstrap to migrate"
            )

        # Use SUBUMBRA_ACCESS_TOKEN as the nominal api_key so LiteLLM sends a
        # valid (non-empty) Bearer header. The transport strips Authorization
        # before packaging the /proxy request and the Worker validates the
        # outer X-Subumbra-Token header.
        kwargs["api_key"] = SUBUMBRA_ACCESS_TOKEN

        # ── 3. Inject V2 envelope headers ─────────────────────────────────────
        if not kwargs.get("extra_headers"):
            kwargs["extra_headers"] = {}

        kwargs["extra_headers"]["X-Subumbra-Token"]       = SUBUMBRA_ACCESS_TOKEN
        kwargs["extra_headers"]["X-Subumbra-Ciphertext"]  = ciphertext
        kwargs["extra_headers"]["X-Subumbra-Provider"]    = provider
        kwargs["extra_headers"]["X-Subumbra-Key-Id"]      = key_id
        kwargs["extra_headers"]["X-Subumbra-Wrapped-Dek"] = wrapped_dek
        kwargs["extra_headers"]["X-Subumbra-Pub-Key-Fp"]  = pub_key_fp or ""

        return kwargs

    # ── optional: log outcomes for UI dashboard ───────────────────────────────

    async def async_log_success_event(self, kwargs: dict, response_obj, start_time, end_time) -> None:
        api_key = kwargs.get("api_key", "")
        if isinstance(api_key, str) and api_key == SUBUMBRA_ACCESS_TOKEN:
            model   = kwargs.get("model", "unknown")
            elapsed = (end_time - start_time).total_seconds()
            log.warning("subumbra-callback: success  model=%s  elapsed=%.2fs", model, elapsed)

    async def async_log_failure_event(self, kwargs: dict, response_obj, start_time, end_time) -> None:
        api_key = kwargs.get("api_key", "")
        if isinstance(api_key, str) and api_key == SUBUMBRA_ACCESS_TOKEN:
            model = kwargs.get("model", "unknown")
            exc   = kwargs.get("exception", "unknown error")
            log.error("subumbra-callback: failure  model=%s  error=%s", model, exc)


# ─────────────────────────────────────────────────────────────────────────────
# Module-level instance — referenced by litellm_settings.callbacks in config.yaml
# LiteLLM imports this module and reads this name directly; the config value
# must be "custom_callbacks.proxy_handler_instance" (instance, not class).
# ─────────────────────────────────────────────────────────────────────────────
proxy_handler_instance = ForgeKeyCallback()

# ── Self-register with LiteLLM (intentionally redundant) ───────────────
# LiteLLM's config resolution via initialize_callbacks_on_proxy() will also
# register this instance. This import-time append is belt-and-suspenders:
# it guarantees the hook is active even if LiteLLM's config processing
# changes in a future version. The try/except catches a potential circular
# import during early initialization — in that case, config-based
# registration is the primary path.
try:
    import litellm as _litellm
    if proxy_handler_instance not in _litellm.callbacks:
        _litellm.callbacks.append(proxy_handler_instance)
except Exception:
    pass  # Will be registered via config instead
